### PR TITLE
fix replace_var function in update_config.sh

### PR DESCRIPTION
**Pull request by the-braveknight**
It is not actually replacing values in 'CLOVER/config.plist' with values in './config.plist'...

### CODE REVIEW

**Comment by RehabMan** [comment]
Your change is not correct.  $config refers to the plist.  Note that update_config.sh is not finished, not for general use.

**Comment by the-braveknight** [comment]
Okay but if $config refers to EFI/Clover/config.plist, what is the point of replacing values in $config with values in $config itself...?

**Comment by RehabMan** [comment]
I don't even remember why I wrote that code...
Like I said, this code is for my internal/personal use only.
You can modify it for your purposes as you see fit.
It is not part of my guide...

**Comment by RehabMan** [comment]
I probably meant to copy from repo config.plist to EFI config.plist, but the only two places it is used is for CsrActiveConfig and BooterConfig, which will always be 0x67 and 0x28 and are never changing, so really there is no issue...

**Pull request closed without merging**
